# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# command_timeout = 1000

[gcloud]
disabled = true

[jobs]
symbol = "✦"
style = "yellow bold"
number_threshold = 1
symbol_threshold = 1
